---
kind: golang.Protobuf
spec:
  vtProtobufEnabled: true
  specs:
    - source: api/events/events.proto
      subdirectory: events/
    - source: api/siderolink/provision.proto
      subdirectory: siderolink/
---
kind: auto.CommandConfig
name: siderolink-agent
spec:
  disableImage: true
