---
kind: golang.Generate
spec:
  vtProtobufEnabled: true
  specs:
    - source: api/events/events.proto
      subdirectory: events/
    - source: api/siderolink/provision.proto
      subdirectory: siderolink/
---
kind: auto.CommandConfig
name: siderolink-agent
spec:
  disableImage: true
---
kind: golang.Build
spec:
  outputs:
    linux-amd64:
      GOOS: linux
      GOARCH: amd64
    linux-arm64:
      GOOS: linux
      GOARCH: arm64
    linux-armv7:
      GOOS: linux
      GOARCH: arm
      GOARM: 7
    darwin-amd64:
      GOOS: darwin
      GOARCH: amd64
    darwin-arm64:
      GOOS: darwin
      GOARCH: arm64
    windows-amd64.exe:
      GOOS: windows
      GOARCH: amd64
---
kind: service.CodeCov
spec:
  targetThreshold: 8
        
